### ISSUE TITLE
Cannot select files after update to 3.61.0

### ISSUE THREAD

**Issue by marce14git** [outlyer-net/docker-losslesscut#3]
After the update i can no longer open the files individually, the files are greyed out.
![image](https://github.com/outlyer-net/docker-losslesscut/assets/92689239/a782da87-7389-42ee-a7b3-204466105814)

It works in the previous version ([3.59.1](https://github.com/outlyer-net/docker-losslesscut/releases/tag/3.59.1-v1)).
However one benefit of the new version is that no .pki folder is created in the storage directory after exporting.

PS: A workaround for this is opening the whole folder and select the files on the left side via "Batch file list"

**Comment by outlyer-net** [comment]
It behaves like this for me using the AppImage too. It appears to be a bug in LosslessCut (see https://github.com/mifi/lossless-cut/discussions/1995 and/or https://github.com/mifi/lossless-cut/issues/2001).

Feel free to reopen this issue if you want to comment further.

I'm nonetheless reverting the `latest` tag to 3.59.1 since 3.61.0 is a pre-release, so if you want to keep using 3.61.0 you'll have to use it explicitly.
I'm yet to decide how to handle pre-releases.
