### ISSUE TITLE
no sound?

### ISSUE THREAD

**Issue by RezzZ** [outlyer-net/docker-losslesscut#4]
I just installed this docker on my unraid server. Unfortunately I don't receive any sound using the browser vnc connection on port 5800. Any suggestions?

**Comment by outlyer-net** [comment]
I'm not familiar with setting up audio redirection, I'm sorry. Leaving this open in case someone else can help at some point.

**Comment by RezzZ** [comment]
I know [LinuxServer.io](https://linuxserver.io/) often uses KASMVNC based gui containers (like with audacity):
https://github.com/linuxserver/docker-audacity?tab=readme-ov-file#options-in-all-kasmvnc-based-gui-containers
Not saying you should move from jlesage/baseimage-gui to kasmvnc but perhaps you could 😆

**Comment by vttc08** [comment]
For now jlesage GUI baseimages support audio via noVNC web browser, it needs an environment variable `WEB_AUDIO=1`. See [here](https://github.com/jlesage/docker-baseimage-gui?tab=readme-ov-file#web-audio) for official documentation. For audio to work, you'll need to install `libpulse` package in the container or `libpulse-dev` since this project uses Debian baseimage. I built the image locally with the change and I've tested the audio work in a web browser.  

For the user to enable audio
- pass through environment variable `-e WEB_AUDIO=1` or equivalent in docker-compose
- click the 3-dot settings icon in the browser VNC page, the new jlesage baseimage now has option for audio

![image](https://github.com/user-attachments/assets/57e8fed2-6cf8-4a45-9185-c7b8f8ac54b0)

**Comment by outlyer-net** [comment]
Should be fixed in the [updated image](https://github.com/outlyer-net/docker-losslesscut/releases/tag/3.61.1-v2)

**Comment by RezzZ** [comment]
works perfectly. any chance though volume can be on at start instead of muted?

**Comment by outlyer-net** [comment]
> works perfectly. any chance though volume can be on at start instead of muted?

I can't see anything specific about it, maybe a request to consider for the base image ([jlesage/docker-baseimage-gui](/jlesage/docker-baseimage-gui))
